### PR TITLE
Compiling Delphi Berlin 10.1

### PR DESCRIPTION
**Pull request by OneideLuizSchneider**

### CODE REVIEW

**Comment by stijnsanders** [comment]
I won't be pulling, please see my most recent commit where I used a single compiler-conditional on top.

**Comment by OneideLuizSchneider** [comment]
ok
Thanks.

**Comment by OneideLuizSchneider** [comment]
Hi
I updated today, but it still does not compile.
berlin-error

**Comment by stijnsanders** [comment]
Could you check (with Ctrl+Click on 'Seek') what is the exact type used in the declaration of IStream in your version?

**Comment by stijnsanders** [comment]
Did some more gophering, appears that older Delphi versions also support `LargeUInt` (but patch it through to `Int64` just as well) Please check if it works with the current master?

**Comment by OneideLuizSchneider** [comment]
Hi,
Missing implementation of interface method IPersistStream.GetSizeMax

image

**Comment by OneideLuizSchneider** [comment]
Hi,
Missing implementation of interface method IPersistStream.GetSizeMax

image

**Comment by stijnsanders** [comment]
Does it compile if you only change `GetSizeMax`' argument to type `Largeint`?

**Comment by OneideLuizSchneider** [comment]
Yes it works in Delphi Berlin, but in Delphi 2010 it does not compile.

image

**Comment by stijnsanders** [comment]
nng, it really would be nice if there were just a single type that works with all, could you please try with `p1,p2:LargeInt;` just one more time, of that doesn't work, I'll put in the `{$IFDEF VER310}`

**Comment by OneideLuizSchneider** [comment]
Hi,
Delphi 2010 Build Ok, in Delphi Berlin erro, according image.
Try to merge a pull request.

image

**Comment by stijnsanders** [comment]
And with LargeUInt?

**Comment by OneideLuizSchneider** [comment]
Error in Delphi 2010 because it is Int64.

image

**Comment by stijnsanders** [comment]
Ok, see my recent commit. I hope this does it. I also hope anyone that knows any version that needs extra contidionals, lets me know.

**Comment by OneideLuizSchneider** [comment]
**Delplhi Berlin** Interface is different. In the **Delphi 2010** interface is also different.
This should be **Largeint**.

image

image

**Comment by stijnsanders** [comment]
ok, hope this is the one

**Comment by OneideLuizSchneider** [comment]
- Should be LargeInt, not another type, OK the interface requires this.
-And in the other image, it should be UInt64 for berlin and int64 for 2010.

 Please see my PULL REQUEST this is correct.

image

image

**Comment by OneideLuizSchneider** [comment]
So compile properly, please review.


[bsonDoc.zip](https://github.com/stijnsanders/TMongoWire/files/834181/bsonDoc.zip)

**Comment by stijnsanders** [comment]
And that compiles in both versions?

**Comment by OneideLuizSchneider** [comment]
Yes, I can do another pull request if it is easier.

**Comment by stijnsanders** [comment]
I've committed something already, please check if it's ok.  Your request has motivated me to look into replacing TMongoWire's bsonDoc with [jsonDoc](https://github.com/stijnsanders/jsonDoc#jsondoc) and a separate unit to load/save to/from BSON, chances are there won't be any IPersistStream involved any more.

**Comment by OneideLuizSchneider** [comment]
Hi
Tested at Delphi 2010 and Berlin. Get, DELETE and upload OK.

If you need help with refraining, just let me know.

image

**Comment by OneideLuizSchneider** [comment]
Hi
It is not correct yet.
Example below is that I have set this correct.

image

**Comment by stijnsanders** [comment]
very very strange

**Comment by OneideLuizSchneider** [comment]
No wonder this is Delphi.

image

**Comment by OneideLuizSchneider** [comment]
Build in Delphi 2010 and Berlin OK.
Thanks for help.

image

**Comment by stijnsanders** [comment]
For your information: I've completed the switch to jsonDoc, and IPersistStream has moved out of the picture. If you switch to v1.1, let me know how it works for you.

**Comment by OneideLuizSchneider** [comment]
Hi, adjust the jsonTools.pas for compilation correctly, image below.

image

**Comment by stijnsanders** [comment]
Ah, I thought it was all fixed with eliminating IPersistStream, but basic IStream is still supported, see my last commit

**Comment by OneideLuizSchneider** [comment]
Hi,
Must be VER310, not VER130. image below.

image

**Comment by stijnsanders** [comment]
I feel stupid now, see my corrective commit

**Comment by OneideLuizSchneider** [comment]
Hi, build ok...

image

**Pull request closed without merging**
